name: proxlink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.0.0+2
  http: any
  connectivity_plus: ^6.1.0
  otp_pin_field: ^1.2.9+1
  dotted_border: ^2.1.0
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  google_sign_in: ^6.1.1
  flutter_facebook_auth: any
  sign_in_with_apple: ^6.1.2
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.5.7

  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  flutter_animate: ^4.0.0
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.1.0
  app_links: ^6.4.1
  device_info_plus: ^12.3.0
  geolocator: ^13.0.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.1.0
  mobile_scanner: ^5.2.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
  fonts:
      - family: ADLaM Display
        fonts:
          - asset: assets/fonts/ADLaMDisplay-Regular.ttf
      - family: Acre
        fonts:
          - asset: assets/fonts/Acre-Regular.ttf
          - asset: assets/fonts/Acre-Bold.ttf
            weight: 700
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter-Regular.otf
          - asset: assets/fonts/Inter-Medium.otf
            weight: 500
          - asset: assets/fonts/Inter-SemiBold.otf
            weight: 600
