// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAf-NUb_zZVsJkblHmLLvFaoNu1mKZUeo',
    appId: '1:1041800447511:web:98c833b524be3d2d8ebe52',
    messagingSenderId: '1041800447511',
    projectId: 'serggo-e3be2',
    authDomain: 'serggo-e3be2.firebaseapp.com',
    storageBucket: 'serggo-e3be2.appspot.com',
    measurementId: 'G-W0TGBZYS0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_of1FUz7y4rbdyQow8XBR-cYcWN9ZeGk',
    appId: '1:1041800447511:android:cefaf3178e6450bf8ebe52',
    messagingSenderId: '1041800447511',
    projectId: 'serggo-e3be2',
    storageBucket: 'serggo-e3be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo5FZE35HLjv6r3jSPxUcB4wsMuWamWV0',
    appId: '1:1041800447511:ios:4670e9ccc80c504e8ebe52',
    messagingSenderId: '1041800447511',
    projectId: 'serggo-e3be2',
    storageBucket: 'serggo-e3be2.appspot.com',
    iosBundleId: 'com.user.serggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo5FZE35HLjv6r3jSPxUcB4wsMuWamWV0',
    appId: '1:1041800447511:ios:4670e9ccc80c504e8ebe52',
    messagingSenderId: '1041800447511',
    projectId: 'serggo-e3be2',
    storageBucket: 'serggo-e3be2.appspot.com',
    iosBundleId: 'com.user.serggo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAf-NUb_zZVsJkblHmLLvFaoNu1mKZUeo',
    appId: '1:1041800447511:web:74a879e52127be848ebe52',
    messagingSenderId: '1041800447511',
    projectId: 'serggo-e3be2',
    authDomain: 'serggo-e3be2.firebaseapp.com',
    storageBucket: 'serggo-e3be2.appspot.com',
    measurementId: 'G-326PTG5WMS',
  );
}
